# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sandro/TCC/Rearranjo-de-Genomas-Cplex-IP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sandro/TCC/Rearranjo-de-Genomas-Cplex-IP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sandro/TCC/Rearranjo-de-Genomas-Cplex-IP/CMakeFiles /home/sandro/TCC/Rearranjo-de-Genomas-Cplex-IP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sandro/TCC/Rearranjo-de-Genomas-Cplex-IP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cplex_Project

# Build rule for target.
Cplex_Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Cplex_Project
.PHONY : Cplex_Project

# fast build rule for target.
Cplex_Project/fast:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/build
.PHONY : Cplex_Project/fast

src/arc.o: src/arc.cpp.o

.PHONY : src/arc.o

# target to build an object file
src/arc.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/arc.cpp.o
.PHONY : src/arc.cpp.o

src/arc.i: src/arc.cpp.i

.PHONY : src/arc.i

# target to preprocess a source file
src/arc.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/arc.cpp.i
.PHONY : src/arc.cpp.i

src/arc.s: src/arc.cpp.s

.PHONY : src/arc.s

# target to generate assembly for a file
src/arc.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/arc.cpp.s
.PHONY : src/arc.cpp.s

src/example1.o: src/example1.cpp.o

.PHONY : src/example1.o

# target to build an object file
src/example1.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/example1.cpp.o
.PHONY : src/example1.cpp.o

src/example1.i: src/example1.cpp.i

.PHONY : src/example1.i

# target to preprocess a source file
src/example1.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/example1.cpp.i
.PHONY : src/example1.cpp.i

src/example1.s: src/example1.cpp.s

.PHONY : src/example1.s

# target to generate assembly for a file
src/example1.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/example1.cpp.s
.PHONY : src/example1.cpp.s

src/ilp.o: src/ilp.cpp.o

.PHONY : src/ilp.o

# target to build an object file
src/ilp.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/ilp.cpp.o
.PHONY : src/ilp.cpp.o

src/ilp.i: src/ilp.cpp.i

.PHONY : src/ilp.i

# target to preprocess a source file
src/ilp.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/ilp.cpp.i
.PHONY : src/ilp.cpp.i

src/ilp.s: src/ilp.cpp.s

.PHONY : src/ilp.s

# target to generate assembly for a file
src/ilp.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/ilp.cpp.s
.PHONY : src/ilp.cpp.s

src/lagrange.o: src/lagrange.cpp.o

.PHONY : src/lagrange.o

# target to build an object file
src/lagrange.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/lagrange.cpp.o
.PHONY : src/lagrange.cpp.o

src/lagrange.i: src/lagrange.cpp.i

.PHONY : src/lagrange.i

# target to preprocess a source file
src/lagrange.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/lagrange.cpp.i
.PHONY : src/lagrange.cpp.i

src/lagrange.s: src/lagrange.cpp.s

.PHONY : src/lagrange.s

# target to generate assembly for a file
src/lagrange.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/lagrange.cpp.s
.PHONY : src/lagrange.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model.o: src/model.cpp.o

.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i

.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s

.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/model_flux.o: src/model_flux.cpp.o

.PHONY : src/model_flux.o

# target to build an object file
src/model_flux.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/model_flux.cpp.o
.PHONY : src/model_flux.cpp.o

src/model_flux.i: src/model_flux.cpp.i

.PHONY : src/model_flux.i

# target to preprocess a source file
src/model_flux.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/model_flux.cpp.i
.PHONY : src/model_flux.cpp.i

src/model_flux.s: src/model_flux.cpp.s

.PHONY : src/model_flux.s

# target to generate assembly for a file
src/model_flux.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/model_flux.cpp.s
.PHONY : src/model_flux.cpp.s

src/prob.o: src/prob.cpp.o

.PHONY : src/prob.o

# target to build an object file
src/prob.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/prob.cpp.o
.PHONY : src/prob.cpp.o

src/prob.i: src/prob.cpp.i

.PHONY : src/prob.i

# target to preprocess a source file
src/prob.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/prob.cpp.i
.PHONY : src/prob.cpp.i

src/prob.s: src/prob.cpp.s

.PHONY : src/prob.s

# target to generate assembly for a file
src/prob.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/prob.cpp.s
.PHONY : src/prob.cpp.s

src/solver.o: src/solver.cpp.o

.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i

.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s

.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/t.o: src/t.cpp.o

.PHONY : src/t.o

# target to build an object file
src/t.cpp.o:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/t.cpp.o
.PHONY : src/t.cpp.o

src/t.i: src/t.cpp.i

.PHONY : src/t.i

# target to preprocess a source file
src/t.cpp.i:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/t.cpp.i
.PHONY : src/t.cpp.i

src/t.s: src/t.cpp.s

.PHONY : src/t.s

# target to generate assembly for a file
src/t.cpp.s:
	$(MAKE) -f CMakeFiles/Cplex_Project.dir/build.make CMakeFiles/Cplex_Project.dir/src/t.cpp.s
.PHONY : src/t.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cplex_Project"
	@echo "... src/arc.o"
	@echo "... src/arc.i"
	@echo "... src/arc.s"
	@echo "... src/example1.o"
	@echo "... src/example1.i"
	@echo "... src/example1.s"
	@echo "... src/ilp.o"
	@echo "... src/ilp.i"
	@echo "... src/ilp.s"
	@echo "... src/lagrange.o"
	@echo "... src/lagrange.i"
	@echo "... src/lagrange.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/model_flux.o"
	@echo "... src/model_flux.i"
	@echo "... src/model_flux.s"
	@echo "... src/prob.o"
	@echo "... src/prob.i"
	@echo "... src/prob.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/t.o"
	@echo "... src/t.i"
	@echo "... src/t.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

